### ISSUE TITLE
STM32FreeRTOS myservo can not work.

### ISSUE THREAD

**Issue by Nanmei** [feilipu/Arduino_FreeRTOS_Library#100]
![1](https://user-images.githubusercontent.com/80303463/110800527-3a14cd80-82b7-11eb-8554-ee347196a9b8.PNG)
![2](https://user-images.githubusercontent.com/80303463/110800538-3d0fbe00-82b7-11eb-8d19-6f6835826f69.png)
`#include <STM32FreeRTOS.h>
#include <Servo.h>    
Servo myservo; 
int pos = 0; 

void vTask1(void *pvParameters){
 myservo.attach(PA7);
  for(;;)
    {
   for(pos = 0; pos < 90; pos += 1){           
      myservo.write(pos);         
       vTaskDelay(20 / portTICK_PERIOD_MS);                  
   }
     vTaskDelay(255 / portTICK_PERIOD_MS); 
    for(pos = 90; pos>=1; pos-=1) {                                 
       myservo.write(pos);            
       vTaskDelay(20 / portTICK_PERIOD_MS);                 
    } 
    vTaskDelay(255 / portTICK_PERIOD_MS);
      
    }
}
void setup() {
  xTaskCreate(vTask1,NULL,64,NULL,1,NULL);
  }
void loop(){
  ;
}`

**This is my code , this code can not work in the STM32FreeRTOS.But this code can work in the arduino.I can't find the reason.**

**Comment by feilipu** [comment]
Sorry, but I can't help you with STM32 code or issues.

Good luck.

**Comment by Nanmei** [comment]
I find the reason thanks
