### ISSUE TITLE
Where is the define of TaskControlBlock_t in task.h?

### ISSUE THREAD

**Issue by thornbirdblue** [feilipu/Arduino_FreeRTOS_Library#112]
Hi feilipu:
I see the origin FreeRTOS code in https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/include/task.h.
The define  of TaskHandle_t is below:
```
struct tskTaskControlBlock; /* The old naming convention is used to prevent breaking kernel aware debuggers. */
typedef struct tskTaskControlBlock * TaskHandle_t;
```
But in your task.h,it is TaskControlBlock_t *.
And I can't search the define of TaskControlBlock_t.

**Comment by feilipu** [comment]
It's an incomplete specification, which is ok if it is completed later. But the [bug](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/89813a3cd32bb8d7aebe27a018bd3e24c6f01ebc/src/tasks.c#L255) is that the actual specification is not updated to match the initial incomplete specification. I believe it is only an issue if you want to delete tasks though.

Will fix soonest. Thanks for noticing.
