### ISSUE TITLE
Issue with delay();

### ISSUE THREAD

**Issue by WildSwan** [feilipu/Arduino_FreeRTOS_Library#132]
**Describe the issue**
delay() function stops the code from continuing.

Sample code:

=================================================================
#include <Arduino_FreeRTOS.h>

void setup() {

  // initialize serial communication at 9600 bits per second:
  Serial.begin(115200);

  delay(1000);

  Serial.println("Setup starts.");    // This wont execute anymore.
  
}

void loop()
{
  // Empty. Things are done in Tasks.
}
=================================================================

**Expected behavior**
"Setup starts." should be displayed on the serial monitor.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser/: Edge
 - Latest
 - Arduino IDE: 2.3.2

**Comment by feilipu** [comment]
`delay()` relies on the scheduler to operate. The scheduler is only initialised on return from the `setup()` function. So your example code can never work.

Do not use `delay` within the `setup` and you will be fine.
