### ISSUE TITLE
Comments on xTaskCreate regarding task priorities are wrong

### ISSUE THREAD

**Issue by joaquimBS** [feilipu/Arduino_FreeRTOS_Library#2]
In both Blink_AnalogRead.ino and AnalogRead_DigitalRead.ino, when creating the tasks the comment says:

// Priority, with 1 being the highest, and 4 being the lowest.

This, based to empirical testing, is wrong. Additionally, the FreeRTOS documentation ([http://www.freertos.org/RTOS-task-priority.html](url)) says

> Low priority numbers denote low priority tasks. 

Regards.

**Comment by feilipu** [comment]
You are correct.
My comment in the code is wrong.
Will fix it in next release.
