### ISSUE TITLE
Compile error on Arduino with configUSE_MALLOC_FAILED_HOOK=0

### ISSUE THREAD

**Issue by Roxy-3D** [feilipu/Arduino_FreeRTOS_Library#41]
Hi!   I started a thread at:

https://sourceforge.net/p/freertos/discussion/382005/thread/3d6c0636/    Because the credits for this user contributed library in Arduino was giving credit to Richard Barry.   Any way...  Long story short...   I'm hoping you can help me!

 I'm trying to slip FreeRTOS under Marlin (the 3D Printing firmware) and have run into a problem. I want to keep trying to xCreateTask() with decreasing amounts of stack memory until the task starts successfully. In order to do that, I need configUSE_MALLOC_FAILED_HOOK=0 (or else the malloc() routines will lock up with the board's LED blinking).

I can't do that because vTaskStartScheduler() makes a call to vApplicationMallocFailedHook();

Can we make a small change in the release version of Arduino's FreeRTOS as described below? It is easy enough to make the change, but the distribution of the needed change is difficult. Marlin uses the GNU license and it would be messy for us to distribute a modified version of FreeRTOS.

```
void initVariant(void)
{
#if defined(USBCON)
    USBDevice.attach();
#endif

    setup();        // the normal Arduino setup() function is run here.

    vTaskStartScheduler(); // initialise and run the freeRTOS scheduler. Execution should never return here.

#if ( configUSE_MALLOC_FAILED_HOOK == 1 )
    vApplicationMallocFailedHook(); // Probably we've failed trying to initialise heap for the scheduler. Let someone know.
#endif
HANG: goto HANG;
      return;
}
```

**Comment by feilipu** [comment]
Updated as per [Richard's suggestion](https://sourceforge.net/p/freertos/discussion/382005/thread/3d6c0636/#2776/7825), in [this commit](https://github.com/feilipu/Arduino_FreeRTOS_Library/commit/ccc1c78f6e58f5ff72929aa6cc5b98f8f96c596f).
