### ISSUE TITLE
`configSUPPORT_STATIC_ALLOCATION` broken with latest update

### ISSUE THREAD

**Issue by Floessie** [feilipu/Arduino_FreeRTOS_Library#51]
Hi Phillip,

`configSUPPORT_STATIC_ALLOCATION` is broken again. Basically you just need to reapply [this commit](https://github.com/feilipu/Arduino_FreeRTOS_Library/pull/19/commits/f8fdd028f1cf29ca086cfa6c848c4f3178e869c1).

Best,
Flössie

**Comment by feilipu** [comment]
Thanks. :+1: 
Fixed with [Release 10.2.0-2](https://github.com/feilipu/Arduino_FreeRTOS_Library/releases/tag/10.2.0-2)
