### ISSUE TITLE
Redefine something in the "FreeRTOSConfig.h" on a user sketch

### ISSUE THREAD

**Issue by JoshuaKim6502** [feilipu/Arduino_FreeRTOS_Library#55]
Hi Phillip,
I enjoy using the FreeRTOS on the Arduino Uno.  I understand why the header file "FreeRTOSConfig.h" is not in an individual project but the Ardunio/libraries/FreeRTOS/src.

What if I put a needed line to my source sketch, while the FreeRTOSConfig.h is intact? I think it works. Correct?

For example, I copy this line to my sketch;

>#undef  configMAX_PRIORITIES
>#define configMAX_PRIORITIES    (1+5)

while the FreeRTOSConfig.h has the original;

>#define configMAX_PRIORITIES    3

It looks work when I compile with no warning message.

Joshua

**Comment by feilipu** [comment]
Joshua,
I'm not sure what will happen.
I suggest that you assign a variable in your sketch with `configMAX_PRIORITIES`, and then print it.
First do it without redefining in your sketch, to ensure you're seeing the original number `(1+5)`, and then again with your redefinition to ensure you see the new number `3`.
Best regards, Phillip

**Comment by JoshuaKim6502** [comment]
Thanks for the comment.  I tested again as you recommend.
Without redefining the `configMAX_PRIORITIES` value, my code prints the original **`3`** as expected.
Once I redefine the value to `6` in my source, the result printed is **`6 = (1+5)`**.
So the redefinition on the user source looks work.

Thanks again, Joshua

**Comment by JoshuaKim6502** [comment]
I misunderstood it. After precise diagnostic concerning the `configMAX_PRIORITIES` value, I realized that redefining it on the user source is meaningless even though it looks to be changed.
The original `<FreeRTOSConfig.h>` dominates compiling kernel codes first off, while any redefined on the user source appears last.
