### ISSUE TITLE
Enhance Documentation

### ISSUE THREAD

**Issue by SpamWall** [feilipu/Arduino_FreeRTOS_Library#59]
The documentation is a little unclear about how to upgrade to the latest FreeRTOS version.  The links take us to the FreeRTOS page, but what then?  Do we just overlay the FreeRTOS files over the Arduino_FreeRTOS src and rebuild?  Does Arduino_FreeRTOS test new versions of FreeRTOS?

Having a couple of paragraphs on this would be very helpful.

**Comment by JoshuaKim6502** [comment]
Please open the Arduino IDE and select  Tools--> Manage Libraries; search "FreeRTOS" and install Richard Barry's.  
![freertos](https://user-images.githubusercontent.com/54395703/65308378-e72bef80-dbc4-11e9-9c83-4473da9d7552.png)

**Comment by JoshuaKim6502** [comment]
This page would help you to start;
https://feilipu.me/2015/11/24/arduino_freertos/

**Comment by feilipu** [comment]
I always try to stay up with the latest version of FreeRTOS, so all that is needed is to install the library using the Aduino Library Manager. Then you're good to go.

As @JoshuaKim6502 has pointed out, there's further info on the web site.
