### ISSUE TITLE
Hope to provide more examples

### ISSUE THREAD

**Issue by Derekduke** [feilipu/Arduino_FreeRTOS_Library#67]
Hi, I really appreciate your work. Do you need more examples? If you need, I can submit some PR about the use of FreeRtOS API.

**Comment by feilipu** [comment]
Sure. Examples are always good.

Would be happy to accept any PRs that illuminate the APIs, particularly for beginners to FreeRTOS.

**Comment by feilipu** [comment]
Thank you. Keep them coming.
