### ISSUE TITLE
FreeRTOS for ESP32

### ISSUE THREAD

**Issue by Rita-GE** [feilipu/Arduino_FreeRTOS_Library#79]
Hi,
You mentioned that this lib implemented for AVR(UNO, Leonardo, Mega). 
But I found that it can be used on ESP32 successfully.
I am so worried about whether it would have a hidden mistake here?

**Comment by feilipu** [comment]
Yes there is assembly language that only works with AVR ATmega in this port. So something will be not working.

Note that FreeRTOS is part of the SDK for ESP32, so perhaps it's using that?
