### ISSUE TITLE
Support for AWS FreeRTOS ESP32

### ISSUE THREAD

**Issue by Yoimer** [feilipu/Arduino_FreeRTOS_Library#99]
Hello there. Awesome work by bringing the powerful FreeRTOS to Arduino boards. 
One question. Is there any way this can be used on ESP32?
Is there any possibility to use AWS FreeRTOS ESP32 demos such as ble, ota and wifi_provisioning with this core of yours?
Looking forward to hearing from you soon.
Thanks in advance.

**Comment by feilipu** [comment]
Yes [AWS fully supports FreeRTOS and most of the libraries you mention](https://www.freertos.org/iot-libraries.html) (having taken over the lead), and the [ESP32 has excellent support](https://github.com/espressif/ESP31_RTOS_SDK), including the whole SDK.

This core is simply cloned from the [ATmega port within FreeRTOS Kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/main/portable/ThirdParty/GCC/ATmega). Actually happened the other way around, but that's a detail.
